name: label-pr-test

on:
  issue_comment:
    types: created

jobs:
  label-pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check comment command
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^/label-data-test$'

      - name: Check out main repository
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: actions/checkout@v2

      - name: Setup node 14 env
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Pull label file test
        if: ${{ steps.regex-match.outputs.match != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run pull-label-file-test
